### ISSUE TITLE
Dependency ranges 0.3.3 has been yanked

### ISSUE THREAD

**Issue by anlumo** [google/ripunzip#72] opened 2024-06-28 16:46 UTC
## Expected Behavior

The crate should work.

## Actual Behavior

cargo output:

```
error: failed to select a version for the requirement `ranges = "^0.3.3"`
candidate versions found which didn't match: 0.4.0
location searched: crates.io index
required by package `ripunzip v1.2.2`
    ... which satisfies dependency `ripunzip = "^1.2.2"` of package `foo v0.1.0 (...)`
```

ranges 0.3.3 has been yanked, that's why it's not found. Projects with an existing Cargo.lock do not show this behavior due to the semantics of cargo.

## Steps to Reproduce the Problem

1. Create a new project with no Cargo.lock
1. Add ripunzip as a dependency.

## Specifications

- Version: 1.2.2
- Platform: Archlinux (shouldn't matter)

**Comment by lunchspider** [comment] 2024-07-01 09:21
fixed it in https://github.com/google/ripunzip/pull/71

**Comment by TTheGlock** [comment] 2024-07-11 12:24
> fixed it in #71

Is it ? I still have the same error

**Comment by veloxl** [comment] 2024-07-25 23:50
I can still reproduce this by running:

```
cargo install ripunzip
```

**Comment by kevlened** [comment] 2024-07-29 04:19
@lunchspider's fork works for me:

`cargo install --git https://github.com/lunchspider/ripunzip --branch main ripunzip`

**Comment by adetaylor** [comment] 2024-08-30 06:49
Hi all, for some reason github hasn't been emailing me about ripunzip issues, so I didn't spot this until I noticed it myself today. Fix incoming!

**Comment by adetaylor** [comment] 2024-09-28 08:58
Fixed now in HEAD.

**Closed by adetaylor** 2024-09-28 08:58 UTC
